In [4]:
import pandas as pd

df = pd.read_excel("/Users/andrewhardaway/code/SavvyCoders/Activities/Class Project/EVRegistrations.xlsx")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 52 entries, 0 to 51
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   State                  52 non-null     object
 1   EV Registration Count  52 non-null     int64
 2   TotalRegCount          52 non-null     float64
 3   StatePopulations       52 non-null     int64
 4   EVRegPer1000residents  52 non-null     float64
 5   EVRegPercTotalReg      52 non-null     float64
 6   EVper1000TotalReg      52 non-null     float64
 7   Unnamed: 7             0 non-null      float64
 8   Unnamed: 8             0 non-null      float64
 9   Unnamed: 9             0 non-null      float64
 10  Unnamed: 10            0 non-null      float64
 11  Unnamed: 11            8 non-null      object
dtypes: float64(8), int64(2), object(2)
memory usage: 5.0+ KB

In [5]:
df

,State,EV Registration Count,TotalRegCount,StatePopulations,EVRegPer1000residents,EVRegPercTotalReg,EVper1000TotalReg,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11
0,Alabama,8730,2.059139e+06,4817678,1.812076,0.004240,4.239636,NaN,NaN,NaN,NaN,NaN
1,Alaska,1970,1.410934e+05,728300,2.704929,0.013962,13.962386,NaN,NaN,NaN,NaN,NaN
2,Arizona,65780,2.258488e+06,6561516,10.025122,0.029126,29.125686,NaN,NaN,NaN,NaN,NaN
3,Arkansas,5140,9.586393e+05,2947036,1.744125,0.005362,5.361766,NaN,NaN,NaN,NaN,NaN
4,California,903620,1.426853e+07,38066920,23.737670,0.063330,63.329588,NaN,NaN,NaN,NaN,NaN
5,Colorado,59910,1.496310e+06,5197580,11.526518,0.040039,40.038503,NaN,NaN,NaN,NaN,NaN
6,Connecticut,22030,1.119278e+06,3592053,6.132983,0.019682,19.682337,NaN,NaN,NaN,NaN,NaN
7,Delaware,5390,1.779800e+05,917060,5.877478,0.030284,30.284293,NaN,NaN,NaN,NaN,NaN
8,District of Columbia,5860,1.992495e+05,633736,9.246753,0.029410,29.410364,NaN,NaN,NaN,NaN,NaN
9,Florida,167990,7.853979e+06,19361792,8.676366,0.021389,21.389158,NaN,NaN,NaN,NaN,NaN
10,Georgia,60120,3.525145e+06,9907756,6.067973,0.017055,17.054620,NaN,NaN,NaN,NaN,NaN
11,Hawaii,19760,4.638735e+05,1392704,14.188227,0.042598,42.597820,NaN,NaN,NaN,NaN,NaN
12,Idaho,5940,5.699644e+05,1599464,3.713744,0.010422,10.421703,NaN,NaN,NaN,NaN,NaN
13,Illinois,66880,4.117589e+06,12868747,5.197087,0.016243,16.242513,NaN,NaN,NaN,NaN,NaN
14,Indiana,17710,2.064554e+06,6542411,2.706953,0.008578,8.578122,NaN,NaN,NaN,NaN,NaN
15,Iowa,6220,1.129061e+06,3078116,2.020717,0.005509,5.509003,NaN,NaN,NaN,NaN,NaN
16,Kansas,7550,8.569887e+05,2882946,2.618849,0.008810,8.809918,NaN,NaN,NaN,NaN,NaN
17,Kentucky,7560,1.567435e+06,4383272,1.724739,0.004823,4.823167,NaN,NaN,NaN,NaN,NaN
18,Louisiana,5880,1.279501e+06,4601049,1.277969,0.004596,4.595540,NaN,NaN,NaN,NaN,NaN
19,Maine,4990,4.157246e+05,1328535,3.756017,0.012003,12.003140,NaN,NaN,NaN,NaN,NaN
20,Maryland,46060,2.076393e+06,5887776,7.822988,0.022183,22.182694,NaN,NaN,NaN,NaN,NaN
21,Massachusetts,49440,1.980433e+06,6657291,7.426444,0.024964,24.964232,NaN,NaN,NaN,NaN,NaN
22,Michigan,33150,2.894828e+06,9889024,3.352201,0.011451,11.451457,NaN,NaN,NaN,NaN,NaN
23,Minnesota,24330,1.729997e+06,5383661,4.519230,0.014064,14.063607,NaN,NaN,NaN,NaN,NaN
24,Mississippi,2420,8.935982e+05,2984345,0.810898,0.002708,2.708152,NaN,NaN,NaN,NaN,NaN
25,Missouri,17870,1.916497e+06,6028076,2.964462,0.009324,9.324304,NaN,NaN,NaN,NaN,NaN
26,Montana,3260,4.636510e+05,1006370,3.239365,0.007031,7.031151,NaN,NaN,NaN,NaN,NaN
27,Nebraska,4570,6.048997e+05,1855617,2.462793,0.007555,7.554971,NaN,NaN,NaN,NaN,NaN
28,Nevada,32950,1.051677e+06,2761584,11.931558,0.031331,31.330922,NaN,NaN,NaN,NaN,NaN
29,New Hampshire,6990,4.581410e+05,1321069,5.291169,0.015257,15.257312,NaN,NaN,NaN,NaN,NaN
30,New Jersey,87030,2.535248e+06,8874374,9.806889,0.034328,34.327999,NaN,NaN,NaN,NaN,NaN
31,New Mexico,7080,6.196897e+05,2080085,3.403707,0.011425,11.425073,NaN,NaN,NaN,NaN,NaN
32,New York,84670,3.112030e+06,19594330,4.321148,0.027207,27.207325,NaN,NaN,NaN,NaN,NaN
33,North Carolina,45590,3.280487e+06,9750405,4.675703,0.013897,13.897327,NaN,NaN,NaN,NaN,NaN
34,North Dakota,640,2.122918e+05,704925,0.907898,0.003015,3.014718,NaN,NaN,NaN,NaN,NaN
35,Ohio,34060,4.086521e+06,11560380,2.946270,0.008335,8.334718,NaN,NaN,NaN,NaN,NaN
36,Oklahoma,16290,1.056367e+06,3818851,4.265681,0.015421,15.420783,NaN,NaN,NaN,NaN,NaN
37,Oregon,46980,1.357126e+06,3900343,12.045094,0.034617,34.617259,NaN,NaN,NaN,NaN,NaN
38,Pennsylvania,47440,3.917586e+06,12758729,3.718239,0.012109,12.109497,NaN,NaN,NaN,NaN,NaN
39,Rhode Island,4340,3.383506e+05,1053252,4.120571,0.012827,12.826932,NaN,NaN,NaN,NaN,NaN
40,South Carolina,13490,1.919529e+06,4727273,2.853654,0.007028,7.027765,NaN,NaN,NaN,NaN,Data Source:
41,South Dakota,1170,3.176966e+05,834708,1.401688,0.003683,3.682759,NaN,NaN,NaN,NaN,Vehicle registration counts derived by the Nat...
42,Tennessee,22040,2.346547e+06,6451365,3.416331,0.009393,9.392526,NaN,NaN,NaN,NaN,NaN
43,Texas,149000,7.784067e+06,26092033,5.710555,0.019142,19.141665,NaN,NaN,NaN,NaN,Notes:
44,Utah,28050,9.907563e+05,2858111,9.814174,0.028312,28.311704,NaN,NaN,NaN,NaN,Only all-electric vehicles are included in thi...
45,Vermont,5260,1.800255e+05,626358,8.397753,0.029218,29.218083,NaN,NaN,NaN,NaN,Registration counts are approximate.
46,Virginia,56610,2.978391e+06,8185131,6.916200,0.019007,19.006907,NaN,NaN,NaN,NaN,"California had approximately 903,620 light-dut..."
47,Washington,104050,2.977074e+06,6899123,15.081627,0.034950,34.950425,NaN,NaN,NaN,NaN,NaN
48,West Virginia,1870,3.594297e+05,1853881,1.008695,0.005203,5.202687,NaN,NaN,NaN,NaN,Worksheet available at afdc.energy.gov/data
49,Wisconsin,15700,1.825450e+06,5724692,2.742506,0.008601,8.600621,NaN,NaN,NaN,NaN,Last updated July 2023
50,Wyoming,840,1.865827e+05,575251,1.460232,0.004502,4.502026,NaN,NaN,NaN,NaN,NaN
51,Total,2442270,1.029739e+08,314107084,7.775278,0.023717,23.717374,NaN,NaN,NaN,NaN,NaN